version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: headband_redis
    restart: always
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: headband_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: headband
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: headband_backend
    restart: always
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: headband_frontend
    restart: always

    env_file:
      - ./.env
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: headband_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: