"""Initial migration

Revision ID: 5a14bc1a5523
Revises: 
Create Date: 2026-07-22 19:02:50.200946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a14bc1a5523'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_bank',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('master_id', sa.UUID(), nullable=False),
    sa.Column('base_sub', sa.BigInteger(), nullable=False),
    sa.Column('partner_sub', sa.BigInteger(), nullable=False),
    sa.Column('change_level', sa.Boolean(), nullable=False),
    sa.Column('stop_sub', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_id')
    )
    op.add_column('admins', sa.Column('chat_id', sa.BigInteger(), nullable=False))
    op.add_column('admins', sa.Column('password', sa.String(), nullable=False))
    op.add_column('admins', sa.Column('creator', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'admins', ['chat_id'])
    op.drop_column('masters', 'moderation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masters', sa.Column('moderation', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_column('admins', 'creator')
    op.drop_column('admins', 'password')
    op.drop_column('admins', 'chat_id')
    op.drop_table('subscription_bank')
    op.drop_table('support_requests')
    # ### end Alembic commands ###
