"""minor_fix_saved

Revision ID: d297f4e0c087
Revises: d7524a7e47e9
Create Date: 2026-07-23 17:37:37.176580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd297f4e0c087'
down_revision: Union[str, Sequence[str], None] = 'd7524a7e47e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('previews', 'saved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('previews', 'saved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
