"""For stats

Revision ID: d7524a7e47e9
Revises: 5a14bc1a5523
Create Date: 2026-07-23 17:26:44.326516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7524a7e47e9'
down_revision: Union[str, Sequence[str], None] = '5a14bc1a5523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.BigInteger(), nullable=False),
    sa.Column('token_type', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('costage', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('masters', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('previews', sa.Column('saved', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('previews', 'saved')
    op.drop_column('masters', 'created_at')
    op.drop_table('token_usage')
    # ### end Alembic commands ###
